### ISSUE TITLE
A published roadmap

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#23]
Would be nice to have a published roadmap. Want to know when BB 2.2, 2.3, 2.4, 3.0, etc. (maybe) comes...

**Comment by az0** [comment]
I posted a basic roadmap here: https://www.bleachbit.org/news/bleachbit-22

The next will release will update GTK to version 3, and the following release will update Python to version 3.

**Comment by Tobias-B-Besemer** [comment]
I thought maybe something with a blurred timeline?
From v2.0 to v2.2 it was a year... Do you think till next release will also take a year? Or what do you think, how many months it will take?

**Comment by az0** [comment]
I would like to release it *much* sooner than a year, not it's hard to give a precise timeline.

**Comment by Tobias-B-Besemer** [comment]
Thank you very much for your answer! :-)
