### ISSUE TITLE
Allow multiple wildcards in path

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#24]
Allow multiple wildcards in path.

This will solve issue https://github.com/bleachbit/bleachbit/issues/392 with:
`<action command="delete" search="walk.all" path="%LocalAppData%\Mozilla\Firefox\Profiles\*\storage\default\*\cache\"/>`
`<action command="delete" search="glob" path="%LocalAppData%\Mozilla\Firefox\Profiles\*\storage\default\*\cache\"/>`

...and makes iTunes Win10 Cleaner work that includes e.g.:
`<action command="delete" search="walk.all" path="%LocalAppData%\Packages\AppleInc.iTunes_*\AC\INet*\"/>`

**Comment by Tobias-B-Besemer** [comment]
Btw.: It is used this way (e.g. "iTunes Win10 Cleaner" AKA "Apple iTunes") in WinApp2.ini and I guess, if it doesn't get included, WinApp2.ini also doesn't work as it should...

**Comment by Tobias-B-Besemer** [comment]
I found this line in google_chome.xml:
`<action command="delete" search="walk.all" path="$$profile$$/Storage/ext/*/*def/GPUCache"/>`

^^

**Comment by az0** [comment]
BleachBit uses [Python's glob ](https://docs.python.org/2/library/glob.html) which supports double wildcards and even fancier patterns, so I added a test to verify and demonstrate. Please see the code referenced above. If I missed a test scenario, let me know.

**Comment by Tobias-B-Besemer** [comment]
I will check if it solves https://github.com/bleachbit/bleachbit/issues/392 with my new Firefox Cleaner (https://github.com/bleachbit/bleachbit/pull/442)... ;-)

**Comment by Tobias-B-Besemer** [comment]
OK, I'm not sure if I did it right... I downloaded BB v2.1.876, started it with my new cleaner and made a preview about the cache cleaning...

...but it showed 0 results!

This is the code my cleaner use:
`<action command="delete" search="walk.all" path="$$localprofile$$\storage\default\*\cache\"/>`
`<action command="delete" search="glob" path="$$localprofile$$\storage\default\*\cache\"/>`

I guess you also don't support 2 wildcards in the path in `walk.all` & `walk.files`, yet...

You can also download my cleaner from my PR and give it a try...
I suggest to run first the FF Cache Cleaner with an old version - then with the new one.
Doing this, you should only see the improvement in the second try...

**Comment by az0** [comment]
The code https://github.com/bleachbit/bleachbit/commit/6f07a27ee1b035e0746d22b30b0dfdca06f35088 was just to verify the existing functionality for search=glob. It didn't add anything new.

search=walk.all should also support multiple wildcard patterns. I'll try to test later

**Comment by Tobias-B-Besemer** [comment]
> search=walk.all should also support multiple wildcard patterns. I'll try to test later

I still don't know if I get it right. This should work:
`<action command="delete" search="walk.all" path="$$localprofile$$\*\demo\storage\*\"/>`

But this not:
`<action command="delete" search="walk.all" path="$$localprofile$$\*\demo\storage\*\*.bak"/>`

Right ???

**Comment by Tobias-B-Besemer** [comment]
My latest firefox.xml pushed in https://github.com/bleachbit/bleachbit/pull/442 solves https://github.com/bleachbit/bleachbit/issues/392! :-)

**Comment by Tobias-B-Besemer** [comment]
> > search=walk.all should also support multiple wildcard patterns. I'll try to test later
> 
> I still don't know if I get it right. This should work:
> `<action command="delete" search="walk.all" path="$$localprofile$$\*\demo\storage\*\"/>`
> 
> But this not:
> `<action command="delete" search="walk.all" path="$$localprofile$$\*\demo\storage\*\*.bak"/>`
> 
> Right ???

And this not:
`<action command="delete" search="walk.files" path="$LocalAppData\Adobe\Acrobat\*\*.dat"/>`

But this works:
`<action command="delete" search="walk.files" path="$LocalAppData\Adobe\Acrobat\*\IconCacheRdr*.dat"/>`

Or how ???

**Comment by Tobias-B-Besemer** [comment]
And what's about `file` ??? Wildcards, yes, but where and how many ???

`<action command="delete" search="file" path="$LocalAppData\Adobe\Acrobat\*\UserCache.bin"/>`
Does it works ???

**Comment by Tobias-B-Besemer** [comment]
@az0, seems you can close this issue, or?

**Comment by Tobias-B-Besemer** [comment]
> BleachBit uses [Python's glob ](https://docs.python.org/2/library/glob.html) which supports double wildcards and even fancier patterns, so I added a test to verify and demonstrate. Please see the code referenced above. If I missed a test scenario, let me know.

Still don't know how to run the test...

> search=walk.all should also support multiple wildcard patterns. I'll try to test later

And I still don't know if "search=walk.files" support multiple wildcards...
Should really know that for the docu...

**Comment by Tobias-B-Besemer** [comment]
Functionality works! ^^ I used the wrong path in my example! ^^

But ... I still don't know this:
> And what's about `file` ??? Wildcards, yes, but where and how many ???
> 
> `<action command="delete" search="file" path="$LocalAppData\Adobe\Acrobat\*\UserCache.bin"/>`
> Does it works ???

And I still don't know this:
> And I still don't know if "search=walk.files" support multiple wildcards...
> Should really know that for the docu...

**Comment by az0** [comment]
> Still don't know how to run the test...

It's an automated test. It is possible to run locally, but it runs automatically on Travis and AppVeyor every time a commit is pushed


> And I still don't know if "search=walk.files" support multiple wildcards...

Yes, it does

>And what's about file ??? 

No, search=file does not supporter any wildcards. 

> Wildcards, yes, but where and how many ???

Wherever a glob pattern is supporter, there is no practical limit on the number of wildcards.

**Comment by Tobias-B-Besemer** [comment]
I add this to the docu...

**Comment by Tobias-B-Besemer** [comment]
Added! ^^
