### ISSUE TITLE
Provide a BB3.0-Cleaner-Package (for Windows XP Users)

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#45]
I think it would be a good idea to provide a BB3.0 (BleachBit v3.0)-Cleaner-(only)-Package (for Windows XP Users).
A lot of cleaners have changed, some improvements are also interesting for Windows XP Users and as BB2.2 was last version with support for Windows XP, so they should get at least the newest Cleaners.
Package can be done with NSIS ZIP2EXE or a real NSIS Installer.
The real NSIS Installer should get some modifications like it is done for "NoTranslations", that it installs without core (but I can do that), or the v2.2 core can be used for the installer.
But the easiest solution would be surly the ZIP2EXE Installer.

**Comment by Tobias-B-Besemer** [comment]
@az0, saw you have released BB3.0.
Should we do now a BB3.0 Cleaner Package for WinXP users ???

**Comment by az0** [comment]
Especially if you want to work on it, I am open to a simple installer of
CleanerML files for Windows XP. You could have options for BleachBit 3.0
core, CleanerML release, and CleanerML pending.

For what it's worth, I didn't try to drop support for Windows XP in
BleachBit 3.0. It came with either GTK+ 3 or one of the other dependency
changes. Also, last I checked WIndows XP was 0.5% of the visitors to the
site, according to Google Analytics.


Andrew

**Comment by Tobias-B-Besemer** [comment]
I don't understand. Install should offer BB3.0 core install but it wouldn't run on WinXP ???

It's easy to modify my install that BB core is not forced, indeed is an option...

...but I can also do 2 ZIP2EXE installer for CleanerML stable & beta...

So what should I do ???

Will try to do it this week...

**Comment by az0** [comment]
By BleachBit 3.0 core, I meant the .xml files that come with the application. (I don't mean the BleachBit application itself.)

**Comment by Tobias-B-Besemer** [comment]
OK, I understand now!
Unfortunately I guess this isn't a work done in some minutes... Would be easy to just install the cleaners and not the prog files... I more see a problem that we then maybe have an installer who says he install BB, but just install the cleaners... and then I have to check and maybe fix strings... and don't know if I will run into other probs...

My suggesten would be to try the ZIP2EXE installer for stable, beta, alpha cleaners (three installer for each group one)...
...and I can provide a complete installer for BB3.0 for those who have problems with the existing one...

What do you think about my suggestions ???

**Comment by Tobias-B-Besemer** [comment]
Here is my BB folder on Google Drive:
https://drive.google.com/drive/folders/1ZbzJimB2rPPaC9zen-5_8frIX5RlCN4M

I made a MUI2 installer with BB3.0...
You find it in the folder NSIS.MUI2.

I made a UMUI installer with BB3.0, too.
I will suggest to focus on this.
I removed the 3 languages you removed and it was much more work with MUI2, because there is all written by me, while UMUI delivers some of the functionality, already...
There are IMHO some space that UMUI gets better, but I will fill issues to it later...
The UMUI installer with BB3.0 is in the folder NSIS.UMUI.Gray.

The folder NSIS.UMUI.SoftGray is outdated but have a other skin/theme...
...so you can have a look on the other (older) skin/theme I made, but you shouldn't use this outdated version...

I thought about making a NSIS installer just for the cleaners, again, and some other problems would be to read the location BB is installed too, remove unnecessary things like the feature to don't create a desktop icon and write the files, but don't register the installer in the system and don't write an uninstall and maybe much more...
In short: It would be a complete new installer (forked from the existing one) and it would be a lot of work...

I created and added the ZIP2EXE installer in the folder NSIS.ZIP2EXE.CleanerML.
Here is/was the problem, that I can't know where the user have BB installed too.
I also found a bug that ZIP2EXE isn't able to handle system environment variables...
...and if the innstaller would be able to do it, we would had the problem again, that we install a 32-bit prog and the variables are different on x32 & x64 Win...
...so I decided to just unzip the files into a folder on the desktop. The user must after that copy/move the content to the cleaner folder. I would suggest to move them into a BleachBit\share\cleaners folder, not the users cleaners folder! Benefit: When the user uninstall BB the cleaners gets removed, too! After that he can install them new or re-install without Beta/Alpha cleaner, but he can't forget them in the users cleaner folder and there can't come issues up because of that.

**Comment by az0** [comment]
How is this https://www.bleachbit.org/download/old ?

**Comment by Tobias-B-Besemer** [comment]
Yeah, works for me!

But will suggest you to at least fix "wil" and to remove a "to" that seems to be to much in the text...

**Comment by az0** [comment]
OK, I fixed the typos in the instructions
