### ISSUE TITLE
Option to minimize to system tray

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#46]
IMHO, when BB installs (or have the option) to start on Windows (Autostart), then BB should also have the option to minimize to system tray.

**Comment by az0** [comment]
I recently removed autostart

**Comment by Tobias-B-Besemer** [comment]
I read it ATM!

Does this mean that Autostart should get removed from the installer, too?

In my last push I had a change that the Autostart Shortcut opens BB minimized...

**Comment by Tobias-B-Besemer** [comment]
Removing the option was also (as far as I understand it) because of failing tests...

I think the option in the installer hurts nobody and can therefor persist...

**Comment by az0** [comment]
I removed autostart from the installer.

I'm not sure many people would use the system tray. If you find many people do, let me know. BleachBit does not run automatically in the background, and it's relatively quick to start (on most systems) when it is needed
