### ISSUE TITLE
Color definitions for BB3.0

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#47]
I tested the latest build of BB3.0 with GTK3 and saw, that the new GUI seems to be dark by default. Now I would modify the installer that he better fits to the new design. My problem is, I can't figure out in which file the color definitions are. So I should get pointed to it...

**Comment by Tobias-B-Besemer** [comment]
OK, I made a screenshot and took the color picker... ^^

This is how it looks now:
![2019-04-24 21_44_04-Installation von BleachBit](https://user-images.githubusercontent.com/11881073/56689046-739bba00-66da-11e9-8bd0-d48d0f09f40a.jpg)
![2019-04-24 21_44_35-Installation von BleachBit](https://user-images.githubusercontent.com/11881073/56689054-77c7d780-66da-11e9-98f3-082fcd158abe.jpg)

**Comment by az0** [comment]
You said you figured it out , so closing
