### ISSUE TITLE
Write chaff to USB sticks and then delete it again to wipe free space

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#63]
Not sure if BB do it already this way, but I think BB should write chaff to USB sticks and then delete it again to wipe free space there (on exFAT).

**Comment by az0** [comment]
The user can already select any directory

**Comment by Tobias-B-Besemer** [comment]
Complete drives with exFAT, too?

**Comment by az0** [comment]
It doesn't erase the file system, and it works with any filesystem.

The chaff files are basically normal text files.

**Comment by Tobias-B-Besemer** [comment]
This was how I understand it... Wanted just to make sure it works with the root of a drive, too.

Btw.: Eraser don't support exFAT yet, because they always try to use the filesystem direct and there is no doc to exFAT, yet. IDK why, but seems they didn't came to the point to write chaff to the drives and erase it after that again, by now, and so BB is able to wipe USB Sticks/microSD were by bigger size exFAT is default, and eraser not. :)
