### ISSUE TITLE
APT sources lists for BB

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#72]
APT use the sources lists defined to look for available packages  and new versions of progs.
If you haven't changed the sources, distry sources are used.
Using distry sources are important to update and keep your distry secure!
But you can add more sources to the list to can choose from more packages and have newer versions (e.g. backports to older distrys versions if you not already run latest).
Unfortunately there is no list that include latest BB! So you have to download and install latest manual!
Would like to see that @az0 creates sources list (automatically) (from CI...) so people e.g. that are involved in development (e.g. SQC) can easily always update to latest build for testing...

Think perfect would be four lists:
- stable-latest: Would include latest BB stable. ATM this would be the following BB4.
- stable-aged: Stable BB, but more conservative, have versions of maintenance releases instead of really latest stable. ATM this would be BB3 maintenance version/build when BB3 maintenance version/build gets released parallel to newest stable version/build BB4.
- unstable-latest: Latest dev build created by CI. (For SQC of build process.)
- unstable-aged: Latest "stable" CI dev build choosen by @az0 for verify of fixed issues and therefor for SQC of next release. (Build selected like ATM for the download page of BB CI builds.)

Note for people who don't know the sources lists of APT:
https://tecadmin.net/add-apt-repository-ubuntu/
https://help.ubuntu.com/community/UbuntuBackports
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=bleachbit
Btw.: You can choose source lists from distry alternatives ("based on" distries), too! So you can e.g. extend your Ubuntu packages list with progs listed in the lists of Mint! (E.g. "create" an install of Mint based on the faster updated sources of Ubuntu...) But the original distry sources should always (if possible) be preferred! (Sort order of sources list...)

**Comment by Tobias-B-Besemer** [comment]
Just FYI:
"Backports apps for Linux Mint 19.x series"
https://launchpad.net/~linuxmint-tr/+archive/ubuntu/backports-app-19

**Comment by az0** [comment]
This sounds like something that has come up several before regarding Chocolately, Snap, PPAs, etc.  I agree automatic updates are great. However, manual downloads drive revenue that supports the development of this application. For example, right now I have several open contracts, and they are paid from these funds. I plan to open more contracts too.

I'm not going to stop people from redistributing BleachBit (I have even helped, in some cases), but if I were to enable and encourage wide-scale automatic updates, I would be "shooting myself in the foot."  Sorry, I just can't "shoot myself in the foot."
