### ISSUE TITLE
Keep BB up-to-date with backports on Unix/Linux

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/wishlist#73]
@az0, think you should at least use the backports repos of Debian & Ubuntu!

https://wiki.ubuntu.com/UbuntuBackports

Will help, if you need help...

**Comment by Tobias-B-Besemer** [comment]
FYI...

https://answers.launchpad.net/ubuntu/+source/bleachbit/+question/686429

https://opensourcehacker.com/2013/03/20/how-to-backport-packages-on-ubuntu-linux/

**Comment by az0** [comment]
While I agree that automatic updates are convenient, this could have long-term negative consequences. Please see here

https://github.com/bleachbit/wishlist/issues/72#issuecomment-560018032

 https://github.com/bleachbit/bleachbit/issues/342#issuecomment-483932944
