### ISSUE TITLE
Please add a package for Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by ghost** [bleachbit/wishlist#87]
The beta of Ubuntu 20.04 Focal Fossa has been released, and final release is scheduled for this Thursday 23rd April. Please add a package for this long-term support release when you get a chance.

**Comment by az0** [comment]
Are you running Ubuntu 20.04 beta now? Try the BleachBit deb package for Ubuntu 19.10, and when I can, I will post a package specifically for Ubuntu 20.04

**Comment by az0** [comment]
Available here https://www.bleachbit.org/news/bleachbit-411-beta
